language: node_js
sudo: required
node_js:
- 8.11.1
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- export TZ='Asia/Shanghai'  # 设置时区
script:
- ./deploy.sh
deploy:
  provider: pages
  skip-cleanup: true
  github-token: GcQwZy-2fMktO08GGdZAMQ
  local-dir: ./sources/.vuepress/dist/ # 根据情况自定义到静态文件输出目录
  target-branch: gh-pages
  verbose: true
  on:
    branch: master
